//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadeEstoque : DbContext
    {
        public EntidadeEstoque()
            : base("name=EntidadeEstoque")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ESTOQUE> TB_ESTOQUE { get; set; }
        public virtual DbSet<TB_ITEM> TB_ITEM { get; set; }
        public virtual DbSet<TB_MOVIMENTACAO> TB_MOVIMENTACAO { get; set; }
        public virtual DbSet<TB_ORDEM> TB_ORDEM { get; set; }
        public virtual DbSet<TB_PESSOA> TB_PESSOA { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
