//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ITEM()
        {
            this.TB_ESTOQUE = new HashSet<TB_ESTOQUE>();
            this.TB_MOVIMENTACAO = new HashSet<TB_MOVIMENTACAO>();
            this.TB_ORDEM = new HashSet<TB_ORDEM>();
        }
    
        public int HANDLE { get; set; }
        public string NOME { get; set; }
        public string CODIGOREFERENCIA { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public Nullable<int> CLASSIFICACAO { get; set; }
        public Nullable<decimal> PESOLIQUIDO { get; set; }
        public Nullable<decimal> PESOBRUTO { get; set; }
        public Nullable<int> UNIDADEMEDIDA { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> CODIGO { get; set; }
        public string CLASSIFICACAONOME { get; set; }
        public string UNIDADESIGLA { get; set; }
        public string CLIENTENOME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESTOQUE> TB_ESTOQUE { get; set; }
        public virtual TB_PESSOA TB_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MOVIMENTACAO> TB_MOVIMENTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ORDEM> TB_ORDEM { get; set; }
    }
}
