//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PESSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PESSOA()
        {
            this.TB_ESTOQUE = new HashSet<TB_ESTOQUE>();
            this.TB_ITEM = new HashSet<TB_ITEM>();
            this.TB_MOVIMENTACAO = new HashSet<TB_MOVIMENTACAO>();
            this.TB_ORDEM = new HashSet<TB_ORDEM>();
        }
    
        public string NOME { get; set; }
        public Nullable<int> CODIGO { get; set; }
        public string CPF { get; set; }
        public string ENDERECO { get; set; }
        public string TELEFONE { get; set; }
        public int HANDLE { get; set; }
        public string OBSERVACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESTOQUE> TB_ESTOQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ITEM> TB_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MOVIMENTACAO> TB_MOVIMENTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ORDEM> TB_ORDEM { get; set; }
    }
}
