//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public int HANDLE { get; set; }
        public Nullable<int> CODIGO { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
    }
}
